server {
  listen 8051;
  root /srv/customer;
  location /topping-media/ { alias /srv/topping-media/; add_header Cache-Control "public, max-age=86400"; }
  location / { try_files $uri $uri/ $uri.html =404; }
}
server {
  listen 8053;
  root /srv/courier;
  location / { try_files $uri $uri/ $uri.html =404; }
}
