FROM node:22-bookworm-slim AS build
WORKDIR /app
COPY . .
RUN npm ci --no-audit --no-fund
RUN npm run build --workspace=@repo/i18n && npm run build --workspace=api
ENV NODE_ENV=production
USER node
EXPOSE 8058
CMD ["node", "apps/api/dist/main.js"]
