import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const svgsDir = path.join(root, 'svgs');
const iconsDir = path.join(root, 'src', 'icons');
const indexPath = path.join(root, 'src', 'index.ts');

const SECONDARY = '#84CC16';

function toPascalCase(name) {
  return name
    .replace(/[^a-zA-Z0-9]+/g, ' ')
    .trim()
    .split(/\s+/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

function extractInner(svg) {
  const match = svg.match(/<svg[^>]*>([\s\S]*)<\/svg>/i);
  if (!match) throw new Error('Invalid SVG');
  return match[1].trim();
}

/** Convert SVG kebab-case attrs to React camelCase (fill-rule → fillRule). */
function toReactAttrs(inner) {
  return inner.replace(/\b([a-z][a-z0-9]*(?:-[a-z0-9]+)+)=/gi, (attrWithEq) => {
    const name = attrWithEq.slice(0, -1);
    // Keep aria-* / data-* as-is (valid in React)
    if (name.startsWith('aria-') || name.startsWith('data-')) {
      return attrWithEq;
    }
    const camel = name.replace(/-([a-z0-9])/gi, (_, c) => c.toUpperCase());
    return `${camel}=`;
  });
}

function transformInner(inner) {
  return toReactAttrs(inner)
    .replace(/\bfill="black"/gi, 'fill={primary}')
    .replace(/\bfill="#000000"/gi, 'fill={primary}')
    .replace(/\bfill="#000"/gi, 'fill={primary}')
    .replace(new RegExp(`\\bfill="${SECONDARY}"`, 'gi'), 'fill={secondary}')
    .replace(/\bfill="#84cc16"/gi, 'fill={secondary}');
}

function componentSource(componentName, inner) {
  return `import type { IconProps } from '../types';

export function ${componentName}({
  size = 24,
  color = 'currentColor',
  secondaryColor = '${SECONDARY}',
  title,
  className,
  style,
  ...props
}: IconProps) {
  const primary = color;
  const secondary = secondaryColor;
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      style={style}
      aria-hidden={title ? undefined : true}
      role={title ? 'img' : undefined}
      {...props}
    >
      {title ? <title>{title}</title> : null}
      ${inner}
    </svg>
  );
}
`;
}

/** Lucide / react-icons friendly aliases used in the monorepo. */
const ALIASES = {
  Home: 'House1',
  Search: 'MagnifyingGlass',
  X: 'CloseX',
  Trash2: 'Trash2',
  Phone: 'Telephone1',
  MessageCircle: 'Chat',
  MapPin: 'MapPin1',
  MapPinned: 'MapPin2',
  Star: 'StarFull',
  FileText: 'File1',
  Settings: 'Gear1',
  HelpCircle: 'QuestionMarkCircle',
  Store: 'Storefront1',
  Bell: 'Bell1',
  SlidersHorizontal: 'SortAscending',
  Banknote: 'PaperMoney',
  Coins: 'HandCoin',
  Loader2: 'ArrowRotateClockwise1',
  Circle: 'ShapeCircle',
  // Brand / misc
  GooglePlay: 'Play',
};

fs.rmSync(iconsDir, { recursive: true, force: true });
fs.mkdirSync(iconsDir, { recursive: true });

const files = fs
  .readdirSync(svgsDir)
  .filter((f) => f.endsWith('.svg'))
  .sort((a, b) => a.localeCompare(b));

const exports = [];

for (const file of files) {
  const base = path.basename(file, '.svg');
  const componentName = toPascalCase(base);
  const svg = fs.readFileSync(path.join(svgsDir, file), 'utf8');
  const inner = transformInner(extractInner(svg));
  const outPath = path.join(iconsDir, `${componentName}.tsx`);
  fs.writeFileSync(outPath, componentSource(componentName, inner), 'utf8');
  exports.push({ componentName, file: `./icons/${componentName}` });
}

const existingNames = new Set(exports.map((e) => e.componentName));
const aliasLines = Object.entries(ALIASES)
  .filter(([alias, target]) => alias !== target && !existingNames.has(alias))
  .map(([alias, target]) => {
    if (!existingNames.has(target)) {
      throw new Error(`Alias target missing: ${alias} -> ${target}`);
    }
    return `export { ${target} as ${alias} } from './icons/${target}';`;
  })
  .join('\n');

const index = `/* Auto-generated by scripts/generate.mjs — do not edit by hand. */
export type { IconProps, IconComponent } from './types';

${exports.map((e) => `export { ${e.componentName} } from '${e.file}';`).join('\n')}

/* Lucide-compatible aliases */
${aliasLines}
`;

fs.writeFileSync(indexPath, index, 'utf8');
console.log(`Generated ${exports.length} icons + ${Object.keys(ALIASES).length} aliases`);
